#???????????????
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  #?????
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/student_system?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
#    map-underscore-to-camel-case: true